### ISSUE TITLE
Add to Error Message

### ISSUE THREAD

**Issue by twmeier** [bigmountainideas/google-geocoder#1]
Is there anyway the error message can be added to the error response on line 124 in /lib/geocoder.js

cb&&cb('Status: '+res.body.status+', Message: '+res.body.error_message);

I am currently getting "REQUEST_DENIED", and it would be very helpful to know the exact reason why.

Thanks

**Comment by jalleyne** [comment]
Hey @twmeier ive update the npm version (0.1.4) with a fix. let me know if that works for you. thanks for logging this.

**Comment by twmeier** [comment]
@jalleyne that works perfectly! Thanks for your fast response! I now see the issue.

**Comment by jalleyne** [comment]
Glad i could help. thanks for choosing this module.
