### ISSUE TITLE
Error: connect ETIMEDOUT 216.58.208.42:443

### ISSUE THREAD

**Issue by StefanBrand** [bigmountainideas/google-geocoder#3]
Hi, ~everything works out as expected, all requests are geocoded~. (Edit: Not all are geocoded. After about 130 loops, the log slows done and eventually halts. Then the timeout error occurs.) After some time, some seconds after node is finished geocoding my address list and I haven't exited it (Win10, 64bit), I get:

```
Error: connect ETIMEDOUT 216.58.208.42:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```
The IP `216.58.208.42:443` is a GoogleAPIs-Server. It seems that the connection is not terminated by `google-geocoder`.

Does anyone have a hint, why the connection times out?

<details><summary>Click to see my code</summary>

```Javascript
parseCSV.then(function(successMessage) {
  console.log(successMessage);
  shops.shopslist.forEach(function(shop) {
    geo.find(shop["Name Retailer/Venue/Museum"]+' '+shop["Address"]+' '+shop["Zipcode"]+' '+shop["City"]+' '+shop.country, function(err,data) {
      if(err) {
        console.log(err);
        i++;
        var sum = i+j;
        console.log(i + '/'+sum+' requests failed!');
        debugger;
      } else {
        try {
          console.log(data[0].location);
          shop.location = data[0].location;
          debugger;
        } catch (err) {
          console.log(err);
          console.log(shop["Name Retailer/Venue/Museum"]+' '+shop["Address"]+' '+shop["Zipcode"]+' '+shop["City"]+' '+shop.country);
        }
      }
    });
  });
});
```
</details>

**Comment by StefanBrand** [comment]
I wrapped the `geo.find()` request with a `setTimeout()` and it seems to work now. It seems that I sent [too many requests per second](https://developers.google.com/maps/documentation/geocoding/usage-limits), although I did not get an error message like `QUOTA_EXCEEDED`.

```Javascript
setTimeout(function() {
  geo.find(shop["Name Retailer/Venue/Museum"]+' '+shop["Address"]+' '+shop["Zipcode"]+' '+shop["City"]+' '+shop.country, function(err,data) {
    //callback
  });
},50);
```
Edit: Not resolved. It still sometimes happens... :(

**Comment by jalleyne** [comment]
hey @StefanBrand, i haven't run into this but i will have to spend some time doing some more debugging. its possible there are too many open connections at a time based on your systems settings. i would check your system ulimits, also depending on the version of node you are using i would check maxSockets

https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_agent_maxsockets

regarding the connection not closing, that may be an issue with the underlying `superagent` lib we had used for this module. Im not aware of any issue with that though.

**Comment by StefanBrand** [comment]
Thanks for the quick response!

I added this to the top of my file:

```Javascript
const http = http('require');
var maxSocketsAgent = http.Agent({maxSockets: 100});
```

Reproducibly, node doesn't hang. I'll test this further, but it seems 
that it really is an issue with too many open connections.

PS.: I have Node 6.10.0

Am 10.03.2017 um 20:47 schrieb Jovan Alleyne:

**Comment by StefanBrand** [comment]
Thanks for the quick response!

I added this to the top of my file:
```Javascript
const http = require('http');
var maxSocketsAgent = http.Agent({maxSockets: 100});
```

Reproducibly, node doesn't hang. I'll test this further, but it seems 
that it really is an issue with too many open connections.

PS.: I have Node 6.10.0
